listen: 0.0.0.0:4873
storage: /verdaccio/storage
plugins: /verdaccio/plugins

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@*/*":
    access: $unauthenticated
    publish: $unauthenticated
    proxy: npmjs
  "**":
    access: $unauthenticated
    publish: $unauthenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }